### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by rosshadden** [pragmagic/godot-nim#1]
Can you explain how to install and use this?  I know you just created and are working on this project and that's of course why there aren't any docs, but I would love to start using it and helping out where I can.

**Comment by rosshadden** [comment]
@endragor to be more specific, what is the entry point?  I compiled and run `apigen.nim`, which successfully created a bunch of nim files as I would expect.  I tried compiling `nimruntime.nim` and `godot.nim`, but start to get errors later on down the pipeline.  In general I can't figure out how to generate the `.so` library file I believe I need to point godot to in order to use the nim bindings.

**Comment by endragor** [comment]
Hmm, this got attention faster than I expected :) Thank you for your interest, @rosshadden. I'll add sample project soon enough (hopefully today) - there are still several fixes that need to be applied to Godot for this to fully work.

**Comment by endragor** [comment]
I added simple project as a setup example: https://github.com/pragmagic/godot-nim/tree/master/examples/simple
It shows how to load/instantiate scenes, handle input, perform actions on game tick. Hopefully this can serve as a starting point. The rest actually comes from Godot API knowledge which you can get from either going through the generated files (in `godotapi` folder) or [official documentation](https://godot.readthedocs.io/en/stable/classes/).

I haven't tested it on Linux so if it doesn't work there (could be because of wrong paths in build script, for example), then please let me know or make a PR that fixes it.

**Comment by rosshadden** [comment]
Awesome, thanks!

By the way, the reason I found this so quickly is that had have been planning to do this for a couple months (I figured I would have to, since Nim isn't as popular as it deserves yet), and coincidentally just sat down this weeks to start seeing what was necessary by looking at existing bindings for other languages. Part of that research involved searching GitHub for "Godot bindings", which surprisingly led me to this which you had literally just started 😂.

**Comment by endragor** [comment]
Alright :) It's actually quite complete already, there are few known bugs that are going to be fixed by the end of the week. We are using it to develop an actual commercial game (actually, in the process of migrating an existing unpublished game from UE4).

**Comment by rosshadden** [comment]
It's still not clear how to generate the `.so` and `.dll` files. Your `nimlib.tres` file references them in a folder called `_dlls`, which isn't present.

With `GODOT_BIN` set to a binary compiled using your kinddom fork, I ran `nake build`, and it worked (after making a symlink to `../../godot/apigen`), but no library files were created.

**Comment by rosshadden** [comment]
That being said, the example works great. So.... I guess I'm chasing something for no reason?  I guess I don't understand why you don't generate the library files.  Anyway I'm going to close this, thanks for your help and for making the project.

**Comment by rosshadden** [comment]
I got it all working. Thanks for your help, and for making the project.  Sorry for the noise---I had made some comments while trying to figure something out, and have since deleted them.

**Comment by endragor** [comment]
`nake build` is supposed to create .so. There is no way the example can work without it :)
And regarding the symlink - yeah, there was one step missing in the instructions. It is to install the library in advance, so that nakefile can access apigen: `https://github.com/pragmagic/godot-nim.git`. Will add that.

**Comment by TiberiumN** [comment]
Yay, much thanks for these bindings!!!!!
Nim is a perfect fit for Godot!
Much thanks again!

**Comment by TiberiumN** [comment]
@endragor but can you make a bit more useful README?

**Comment by TiberiumN** [comment]
@endragor can you please give links to the PR's that are required to use default godot branch?

**Comment by endragor** [comment]
https://github.com/godotengine/godot/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Aendragor%20

Only https://github.com/godotengine/godot/pull/9721 is left and we discussed a different approach with @karroffel. I'll implement it today and release v0.3.0, there is a bunch of changes incoming. I'll add documentation when everything works as expected.

**Comment by TiberiumN** [comment]
@endragor ok, thanks!

**Comment by TiberiumN** [comment]
@endragor so we can use prebuilt godot now?

**Comment by endragor** [comment]
The fork is not required anymore, you can use godot's official `master` branch: https://github.com/godotengine/godot

**Comment by TiberiumN** [comment]
@endragor I have an issue compiling godot-nim on Windows:
Invalid GODOT_BIN path: "E:\godot\bin\godot.windows.opt.tools.32.exe"

**Comment by TiberiumN** [comment]
Ah, it seems that it doesn't like quotes in path to bin

**Comment by r3d9u11** [comment]
@endragor Sorry, I never used Godot and godot-nim, yet. Does godot-nim using GDNAtive for communication with Godot?

**Comment by rosshadden** [comment]
Yeah man, GDNative, or whatever they are calling it these days.

**Comment by r3d9u11** [comment]
@rosshadden sorry for another stupid question: can game with nim be ported to mobile platforms?

**Comment by rosshadden** [comment]
Maybe I don't understand your question, but the languages you use to program a game---whether they are built-in or through gdnative---have nothing to do with Godot's export capabilities.
