### ISSUE TITLE
Default values to functions vec2 and vec3.

### ISSUE THREAD

**Issue by kakoeimon** [pragmagic/godot-nim#12]
Currently I cannot use vec2() or vec3() I get an error, but I have to use for example vec2(0.0 , 0.0).

**Comment by endragor** [comment]
Nim zero-initializes everything by default, so I don't think no-arg versions are needed for those. Just declare a vector and it will be zero-initialized.

**Comment by kakoeimon** [comment]
Yes you are right, thanks.

By the way, it looks like that it was a mistake from my part to include vec3 in the issue cause vec3() exists.

**Comment by endragor** [comment]
Ah, alright, added vec2() for consistency.
