### ISSUE TITLE
nakefile.nim(5, 8) Error: cannot open 'godotapigen'

### ISSUE THREAD

**Issue by ratherAnonymous** [pragmagic/godot-nim#14]
I followed the steps described in the [documentation](https://pragmagic.github.io/godot-nim/master/index.html#modules-godot-api.).
But I seem to be missing the "godotapigen" module.
Could you tell me where I could get that?

**Comment by endragor** [comment]
Have you performed the steps described here: https://github.com/pragmagic/godot-nim-stub ? Specifically, it seems you are missing `nimble install godot`.

**Comment by ratherAnonymous** [comment]
When installing the godot package with nimble I get the following install log:
Downloading https://github.com/pragmagic/godot-nim using git
   Warning: Package 'godot' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'godot', but file 'godotnim.nim' is in a directory named 'nim' instead. This will be an error in the future.
      Hint: If 'nim' contains source files for building 'godot', rename it to 'godot'. Otherwise, prevent its installation by adding `skipDirs = @["nim"]` to the .nimble file.
  Verifying dependencies for godot@0.7.5
      Info: Dependency on compiler@>= 0.17.3 already satisfied
  Verifying dependencies for compiler@0.17.3
 Installing godot@0.7.5
   Success: godot installed successfully.

**Comment by endragor** [comment]
And then `nake build` fails for you? Could you please also provide output of `nim -v` and `nimble -v`?

**Comment by ratherAnonymous** [comment]
nimble v0.8.8
Nim Compiler Version 0.17.3
I compile Nim right from the git repo. And people told me it's basically 0.18.0.
I don't know where I could get a newer nim version.

**Comment by endragor** [comment]
Not quite sure then why it fails for you... Any chance you have `--noNimblePath` specified in global Nim config?

**Comment by ratherAnonymous** [comment]
Ok, apparently Nim had some problem finding system.nim and other minor things.


Could you tell me how  exactly am I supposed to set the godot environment variable?(I'm on Arch Linux)
right now it's: 
export GODOT_BIN=$PATH:$HOME/Desktop/Godot_v3.0-stable_x11.64

**Comment by Yardanico** [comment]
@ratherAnonymous remove "$PATH:" from this line :)

**Comment by endragor** [comment]
@ratherAnonymous Can I assume this is resolved now and was some kind of environment configuration problem?

**Comment by ratherAnonymous** [comment]
It was an environment configuration problem. 
Thanks for the help. Everything works now. 
:3

**Comment by endragor** [comment]
Good to know!
