### ISSUE TITLE
Cannot open include file: 'windows.h'

### ISSUE THREAD

**Issue by exts** [pragmagic/godot-nim#15]
The error I got running `nake build` after updating to nim version 0.17.3

```
Error: execution of an external compiler program 'vccexe.exe /c --platform:amd64 /nologo /Z7 -DWIN32_LEAN_AND_MEAN /Od  /ID:\Nim\lib /FoZ:\Programming\Nim\Godot\Nimbreak\src\.nimcache\windows\amd64\stdlib_dynlib.obj Z:\Programming\Nim\Godot\Nimbreak\src\.nimcache\windows\amd64\stdlib_dynlib.c' failed with exit code: 2

"C:\WINDOWS\system32\cmd.exe" /C ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64 && SET"
cl.exe /c /nologo /Z7 -DWIN32_LEAN_AND_MEAN /Od /ID:\Nim\lib /FoZ:\Programming\Nim\Godot\Nimbreak\src\.nimcache\windows\amd64\stdlib_dynlib.obj Z:\Programming\Nim\Godot\Nimbreak\src\.nimcache\windows\amd64\stdlib_dynlib.c
stdlib_dynlib.c
Z:\Programming\Nim\Godot\Nimbreak\src\.nimcache\windows\amd64\stdlib_dynlib.c(11): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
       Tip: 11 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "D:\Nim\bin\nim.exe" c --noNimblePath --path:"C:\Users\XXXX\.nimble\pkgs\godot-0.7.7" --path:"C:\Users\XXXX\.nimble\pkgs\compiler-0.17.3" "-o:..\_dlls\nim_64.dll"  "..\src\stub.nim"
```

Let me know if there's anything I can try to sort this issue out, for now I'm just going to create an issue.

**Comment by endragor** [comment]
It's possible that some dependencies of the VS compiler are missing. Can you try installing build tools http://landinghub.visualstudio.com/visual-cpp-build-tools and see if the issue still occurs?

**Comment by exts** [comment]
Yeah it works now with 2017's build tools rather than 2015 for some reason. I had a problem building godot in general yesterday until I used 2017 as well. For some odd reason last week I could build godot's source with 2015 and all of a sudden it just didn't want to work anymore so yeah. I'll close this as it's working now. Could be a reference for anyone else running into this problem :)
