### ISSUE TITLE
Opening a file doesn't work

### ISSUE THREAD

**Issue by bitstopper** [pragmagic/godot-nim#16]
It seems to me that this low level call fails:

fileOpenMethodBind.ptrCall(self.godotObject, argsToPassToGodot, ptrCallRet)

calling 'fileExists' with the same path works and at the C++ level the file also must be open to checked if the file exists, see:

/godot/core/os/file_access.cpp

**Comment by endragor** [comment]
Could you please clarify how exactly it doesn't work for you? This is how it's supposed to be used, and it works for me:

```nim
import godottypes, file

proc workWithSomeFile(path: string) =
  let file = gdnew[godottypes.File]()
  if file.open(path, READ) == Error.OK:
    # work with the file
  else:
    # handle the error
```
