### ISSUE TITLE
Node2d globalPosition should be Vector2

### ISSUE THREAD

**Issue by rosshadden** [pragmagic/godot-nim#20]
In the generated godotapi, `Node2d`'s `globalPosition` is a `float64` instead of `Vector2`. I'm not sure where to file this, but in looking through the godot source code everywhere I see `get_global_position` it is a vector2/point2 type, not a float.

```nim
proc globalPosition*(self: Node2D): float64 {.gcsafe, locks: 0.}
proc `globalPosition=`*(self: Node2D; val: float64) {.gcsafe, locks: 0.}
```

**Comment by endragor** [comment]
There is a mistake in how the property is registered in Godot, I made a PR to fix it: https://github.com/godotengine/godot/pull/18391

Property types are provided manually in Godot code and are not derived from getter/setter types, which makes them prone to human errors. So I also updated godot-nim to use getter return type for properties, making it immune to such errors.
