### ISSUE TITLE
How to use external C/C++ libraries?

### ISSUE THREAD

**Issue by rama0x9** [pragmagic/godot-nim#25]
Hi,
im new to nim in general so i need some help. 
e.g. i want to use https://github.com/Auburns/FastNoise in my project.  

I tried to write a wrapper module for testing but without any luck. For now i want the GetValue Function.

fastnoise.nim 
```Nim
{.push header: "FastNoise.h".} 

type
  FastNoise* {.importcpp: "FastNoise".} = object

#proc constructFastNoise*(seed: cint = 1337): FastNoise {.constructor.}
proc GetValue*(this: FastNoise, x: cfloat, y: cfloat): cfloat {.importcpp.}
#proc SetSeed*(this: FastNoise; seed: cint) {.importcpp.}

{.pop.}
```

generate.nim
```Nim
proc GetNoise() =
    var obj: FastNoise
    print($obj.GetValue(5, 8))
```

First, where to put .h and .cpp files? and what is the path? do i need to link them anywhere? In the example above the compiler can't even find the FastNoise.h, I put it together with generate.nim and fastnoise.nim in /src.

And is the code above the right way to do it? It's my second day with nim, so please bear with me.

**Comment by endragor** [comment]
1. Don't use `push`/`pop` for specifying header, put it as a pragma in the corresponding proc/type.
2. .importcpp expects pattern as a value.
3. Use `.compile` pragma to compile .cpp file along with Nim files.
4. Use `--cincludes:DIR` to specify where to look for the header file.

This information can be found in the [Nim manual](https://nim-lang.org/docs/manual.html).

Try this:

```nim
{.compile: "FastNoise.cpp".}

type
  FastNoise* {.header: "FastNoise.h", importcpp: "FastNoise".} = object

proc GetValue*(this: FastNoise, x: cfloat, y: cfloat): cfloat {.header: "FastNoise.h", importcpp: "#.GetValue(@)".}
```

**Comment by rama0x9** [comment]
>1. Ok, but why? 
>2. I thought the name is taken from the procedure name and you only need it when you want a different name?
>3. gotcha
>4. im having problems with this

i did a quick test with a simple non godot project with a structure like so:
```
C:/Test/main.nim
C:/Test/fastnoise.nim
C:/Test/lib/FastNoise.h
C:/Test/lib/FastNoise.cpp
```
 fastnoise.nim has the code you have kindly posted, then i use
`nim c --cincludes:"C:\Test\lib\" --run "C:\Test\main.nim"`
i get this error:
`Error: unhandled exception: cannot open: FastNoise.cpp [IOError]`

It's beginner level, i know :) but working with godot and external libs is important for me, i need to get this going. I want to take a switch from C# godot because i really like nim so far.

And in an actual godot project, how to use --cincludes with "nake build"? maybe in the nakefile.nim somewhere? or do i need to compile it once with nim? 

 
thanks for your time

**Comment by rama0x9** [comment]
ok, im one step further.
cincludes only with root folder 
`nim c --cincludes:"C:\Test" --run "C:\Test\main.nim"`
and in fastnoise.nim the subfolder:
`{.compile: "lib/FastNoise.cpp".}`

new error:

```
In file included from C:\Test\nimcache\main.c:11:0:
C:\Test/lib/FastNoise.h:45:1: error: unknown type name 'class'
 class FastNoise
 ^~~~~
C:\Test/lib/FastNoise.h:46:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 {
 ^
C:\\Test\nimcache\main.c: In function 'GetNoise_9cku33tvANHm87a2gL2qUHQ':
C:\\Test\nimcache\main.c:80:2: error: unknown type name 'FastNoise'
  FastNoise obj;
  ^~~~~~~~~
C:\\Test\nimcache\main.c:87:11: error: request for member 'GetValue' in something not a structure or union
  T2_ = obj.GetValue(5.0000000000000000e+000, 8.0000000000000000e+000);
```

**Comment by endragor** [comment]
`godot-nim-stub` sample uses C backend to compile the code. You need to modify it to use C++. The line that compiles the main file is the last one in the `build` task of the nakefile: https://github.com/pragmagic/godot-nim-stub/blob/54e5d5c2526262b6e3a0b293676465b5bf615b88/nakefile.nim#L45

Change `c` to `cpp` and add any other parameters you need.

Re push/pop, I think they simply don't work in a way you used them. They can be used to override compiler settings, but not to assume that everything has a certain pragma on it.

And yeah, if you duplicate names it isn't necessary to specify them as .importcpp pragma values, but to be consistent with Nim style it's better to change the method name to lowercase. So in the end you should have something like this:

```nim
{.compile: "lib/FastNoise.cpp".}

type
  FastNoise* {.header: "FastNoise.h", importcpp.} = object

proc getValue*(this: FastNoise; x, y: cfloat): cfloat {.header: "FastNoise.h", importcpp: "GetValue".}
```

It's been a while since I last dealt with C++ interop, so might be something else that's needed here.

**Comment by rama0x9** [comment]
ok, fixing the test project above was simple, `c` to `cpp`
 `nim cpp --cincludes:"C:\Test\lib\" --run "C:\Test\main.nim"` is working, GetValue does its job, nice

now to godot, not so easy though :/
changing `c` to `cpp `only gives error `LNK2019: unresolved external symbol` and `nim64.dll: Fatal Error LNK1120: 1 unresolved externals`
also `Error: execution of an external program failed: 'vccexe.exe`
