### ISSUE TITLE
CanvasItem drawPolygon NilAccess

### ISSUE THREAD

**Issue by DGWana** [pragmagic/godot-nim#26]
While trying to draw a polygon with the ```drawPolygon``` or ```drawColoredPolygon``` functions of a CanvasItem node, I get the following error
```
ERROR: : Unhandled Nim exception (NilAccessError):
godotmacros.nim(569)     methFunc
map2D.nim(57)            draw
canvas_item.nim(797)     drawPolygon
godotnim.nim(433)        godotObject
```
I'm using the function as follow:
```nim
drawPolygon(points, colors, newPoolVector2Array())
```

I think the problem is I'm using the default value of the texture which is nil, and the code tries to pass this nil texture as a godot object:
```nim
proc drawPolygon(self: CanvasItem; points: PoolVector2Array; colors: PoolColorArray;
                uvs: PoolVector2Array; texture: Texture = nil;
                normalMap: Texture = nil; antialiased: bool = false) =
...
let argToPassToGodot3 = texture.godotObject # <= This is the line 797 of canvas_item.nim
```

Am I supposed to pass a not nil texture for this to work? I just want to draw a filled polygon with plain color.

**Comment by DGWana** [comment]
Still not working for me. I have the same error despite the changes. I'm using version 0.7.13

**Comment by endragor** [comment]
You need to re-generate the Godot API wrappers. If your project is based on the stub, do `nake clean`, then `nake build`.

**Comment by DGWana** [comment]
Thanks, was that, I didn't make a proper cleaning
