### ISSUE TITLE
How to register a signal in GodotNim?

### ISSUE THREAD

**Issue by zetashift** [pragmagic/godot-nim#29]
Following this: http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html
I'm almost done except the `signal hit` part which I need to add. I found the `emitSignal` proc and some other stuff related that I tried but nothing came up in the godot editor as a hit signal. Is it possible?

**Comment by endragor** [comment]
You can do it this way:

```nim
method init() =
  addUserSignal("hit")
```

**Comment by zetashift** [comment]
ah yes I stumbled upon the addUserSignl proc but just put it as a field andd got an undeclared field /property error.

Thanks!
