### ISSUE TITLE
Building fails on current devel

### ISSUE THREAD

**Issue by rama0x9** [pragmagic/godot-nim#32]
untouched godot-nim-stub, running on arch linux 
```nim
[rama@home myproject]$ nake build
Compiling nakefile...
OpenGL ES 3.0 Renderer: GeForce GTX 1070/PCIe/SSE2
Generating audio_stream_player_2d.nim...
Generating shape_2d.nim...
Generating dynamic_font_data.nim...
Generating light_2d.nim...
Generating primitive_mesh.nim...
Generating shader.nim...
Generating mobile_vr_interface.nim...
Generating scene_tree_timer.nim...
Generating editor_file_dialog.nim...
Generating packed_scene.nim...
Generating visual_script_function.nim...
Generating animation.nim...
Generating visual_script_sub_call.nim...
Generating video_player.nim...
Generating http_client.nim...
Generating sky.nim...
Generating animation_player.nim...
Generating sprite_base_3d.nim...
Generating polygon_path_finder.nim...
Generating capsule_mesh.nim...
Generating visual_script_constructor.nim...
Generating kinematic_collision.nim...
Generating geometry_instance.nim...
Generating groove_joint_2d.nim...
Generating translation_server.nim...
nake.nim(93)             moduleHook
nakelib.nim(252)         runTask
nakefile.nim(29)         :anonymous
nakefile.nim(26)         genGodotApi
godotapigen.nim(1002)    genApi
renderer.nim(1442)       renderTree
renderer.nim(635)        gstmts
renderer.nim(546)        gsub
renderer.nim(1254)       gsub
renderer.nim(609)        gsection
renderer.nim(1160)       gsub
renderer.nim(546)        gsub
renderer.nim(1127)       gsub
renderer.nim(546)        gsub
renderer.nim(1167)       gsub
renderer.nim(546)        gsub
renderer.nim(1174)       gsub
renderer.nim(1341)       gsub
renderer.nim(321)        gcoms
renderer.nim(318)        gcom
renderer.nim(226)        putComment
system.nim(2857)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```
and with an existing project:
```nim
stub/game/world/character/blocky/player.nim(5, 7) template/generic instantiation from here
/home/rama/.nimble/pkgs/godot-0.7.14/nim/godotmacros.nim(403, 35) Error: undeclared field: ''
```

**Comment by endragor** [comment]
devel gets breaking changes all the time, I intend to apply fixes once the new version is released. Also, when using devel, remember to install latest Nim compiler to the nimble repo: do `nimble install` from Nim's folder. That should fix your first error.

**Comment by rama0x9** [comment]
not working on first error, after doing `nimble install` in the devel folder `~.choosenim/toolchains/nim-#devel/` and then `nake build` i get 
```nim
[...]
Hint: rodutils [Processing]
/home/rama/.nimble/pkgs/godot-0.7.14/godotapigen.nim(9, 26) Error: type mismatch: got <string>
but expected one of: 
proc getIdent(self: IdentCache; identifier: string): PIdent
proc getIdent(self: IdentCache; identifier: string; h: Hash): PIdent
proc getIdent(self: IdentCache; identifier: cstring; length: int; h: Hash): PIdent

expression: getIdent(ident)
``` 
I understand that it's tedious to keep up with the regular changes on devel, so don't worry, i don't need the latest. I only need a working devel build because there are some nim packages which require >0.18.1 and i want to use them.

**Comment by endragor** [comment]
Did you also `nake clean` after installing the devel? `nakefile` needs to be recompiled since it depends on Nim compiler through godot API generator module.

**Comment by rama0x9** [comment]
sure, it's the first thing i do if something not working. 
But in this case with `compiler 0.18.1`, `nake clean` breaks everything because if i build with stable, switch to devel and build without clean, it compiles. 
But If i clean with stable, switch to devel and then build, this error happens, now both `nake build` & `nake clean` are showing that error, even after i switch back to stable. To make it work again i need to remove `compiler 0.18.1`

**Comment by Zireael07** [comment]
I am having the same error:
/home/rama/.nimble/pkgs/godot-0.7.14/godotapigen.nim(9, 26) Error: type mismatch: got <string>
but expected one of: 
proc getIdent(self: IdentCache; identifier: string): PIdent
proc getIdent(self: IdentCache; identifier: string; h: Hash): PIdent
proc getIdent(self: IdentCache; identifier: cstring; length: int; h: Hash): PIdent

expression: getIdent(ident)

**Comment by zetashift** [comment]
@Zireael07 are you using Nim v0.18 or 0.19?

**Comment by Zireael07** [comment]
0.18

**Comment by zetashift** [comment]
@Zireael07 I can't reproduce your error. I cloned the godot-nim-stub and ran `nake build` and it compiles fine. Using v0.18 and windows 10

**Comment by zetashift** [comment]
```Hint: godotstrings [Processing]
..\..\..\.nimble\pkgs\godot-0.7.17\internal\godotstrings.nim(41, 8) Error: usage of 'isNil' is a user-defined error
       Tip: 11 messages have been suppressed, use --verbose to show them.
```
Yeah, hoping that fixing the 0.19 changes will be easy. Will the new version also work with 3.1?

**Comment by zacharycarter** [comment]
I think there are two separate issues being discussed now - one regarding choosenim and pinned compiler versions and another regarding API codgen errors.

The latter issue can be solved by changing any calls to `getIdent` in godotapigen.nim to include an indentCache.

I created one in this file - `var gic* = newIdentCache()` - and then used it as the first argument to all `getIdent` calls in that file. With 0.18.0, this code compiled fine.

I can issue a PR if desired

**Comment by jrenner** [comment]
Hi, I'm running into the `.nimble/pkgs/godot-0.7.17/godotapigen.nim(9, 26) Error: type mismatch: got <string>` error. What's the best way to deal with this currently?
