### ISSUE TITLE
Cannot compile on windows 10?

### ISSUE THREAD

**Issue by codem4ster** [pragmagic/godot-nim#35]
Cannot generate dll file on windows. I install visual studio 2017 and c++ build tools. I found there cl.exe and added to path (because nim cannot find it). At the end this time it says below message;  
```
Error: execution of an external compiler program 'vccexe.exe /c --platform:amd64 /nologo /Z7 -DWIN32_LEAN_AND_MEAN /Od  /IC:\nim\lib /FoD:\gamedev\castle_fight\src\.nimcache\windows\amd64\stub_stub.obj D:\gamedev\castle_fight\src\.nimcache\windows\amd64\stub_stub.c' failed with exit code: 2

cl.exe /c /nologo /Z7 -DWIN32_LEAN_AND_MEAN /Od /IC:\nim\lib /FoD:\gamedev\castle_fight\src\.nimcache\windows\amd64\stub_stub.obj D:\gamedev\castle_fight\src\.nimcache\windows\amd64\stub_stub.c
stub_stub.c
C:\nim\lib\nimbase.h(255): fatal error C1083: Cannot open include file: 'limits.h': No such file or directory
       Tip: 11 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "C:\nim\bin\nim.exe" c --noNimblePath --path:"C:\Users\oelibol\.nimble\pkgs\godot-0.7.14" --path:"C:\Users\oelibol\.nimble\pkgs\compiler-0.18.0" "-o:..\_dlls\nim_64.dll"  "..\src\stub.nim"
```
I tried to find limits.h in visual studio and added to `INCLUDE` env variable that path but this time it cannot find `stddef.h`. Am I missing something?

**Comment by endragor** [comment]
Nim has a problem detecting VS 2017 and running the necessary scripts: https://github.com/nim-lang/Nim/issues/6540

You shouldn't specify `cl.exe` in your PATH. The proper way to set up environment for invoking VS compiler is to run `<VS folder>/VC/vcvarsall.bat <arch>`, where `arch` is `amd64` or `i386` or another target architecture.

As a workaround you can run vcvarsall.bat on your own before running `nake build` and modify `nim.cfg` to include:

```
vcc.exe = "cl.exe"
vcc.cpp.exe = "cl.exe"
vcc.linkerexe = "cl.exe"
vcc.cpp.linkerexe = "cl.exe"
```

**Comment by codem4ster** [comment]
Thanks endragor now I could compile it :)
