### ISSUE TITLE
Nested project folder

### ISSUE THREAD

**Issue by rosshadden** [pragmagic/godot-nim#4]
I've tried a couple times throughout the history of this project to have everything in `project` live at the root directory instead, so that godot's `res://` root can access the root dir.  I was never able to get it working, despite updating all paths that refer to `project`, and all relative paths.

I'm fine working against the grain on this assuming I can get it working, but it makes me want to ask why you made project a subdirectory.  I feel like it doesn't make sense to have to arbitrarily put all assets (including images, models, and other gdscript-agnostic files) inside a nested folder in the project.

I know this is a rather minor complaint, but I'm making a [godot yeoman generator](https://github.com/acleverpun/generator-godot) that will have godot-nim integration from the beginning, and conditionally nesting the godot files based on whether users want to use nim is really weird and wouldn't play well with other languages people might add in the future, but always nesting it is just as weird since it doesn't make any sense in a normal godot project.

**Comment by endragor** [comment]
This should work for you: https://github.com/pragmagic/godot-nim-stub
