### ISSUE TITLE
Nim 0.19

### ISSUE THREAD

**Issue by DwanaG** [pragmagic/godot-nim#41]
I'm just wondering if the bindings are going to be updated to compile with the latest nim version 0.19. As of now, there is the error:

> godotapigen.nim(9, 26) Error: type mismatch: got \<string>
but expected one of:
proc getIdent(ic: IdentCache; identifier: string): PIdent
proc getIdent(ic: IdentCache; identifier: string; h: Hash): PIdent
proc getIdent(ic: IdentCache; identifier: cstring; length: int; h: Hash): PIdent
>
> expression: getIdent(ident)

which can be solved as mentioned in https://github.com/pragmagic/godot-nim/issues/32#issuecomment-435637015. But after that, there are still errors regarding string nil checks (strings can't be nil anymore in 0.19). And even if I use the option --nilseqs:on for backwards compatibility other errors show up. I would love to see the Nim bindings updated,

**Comment by zetashift** [comment]
On the gitter/irc chat @endragor is saying the update will be made soon(TM). However it's because they want to keep the update backwards compatible it can't be done easily I think(they're using it in production).
Currently I'm just using 0.18 as choosenim doesn't work on windows 64bit, so I'd also like to see the update.

**Comment by zetashift** [comment]
@endragor anyway we can contribute, maybe start a branch?

**Comment by zetashift** [comment]
@endragor anyway who could get some updates? I'm getting `{.this.} pragma deprecrated` all over my editor. Doesn't need to be a full blown update, maybe a simple a message about we could go further?

**Comment by Zireael07** [comment]
Any news?

**Comment by Skaruts** [comment]
Speaking of updates, if you don't mind me asking here, I'd like to know if these bindings are planned to also work with Godot 3.1 in the foreseeable future? (I can't use 3.0 because I need gles2.)

**Comment by adrianperreault** [comment]
@Skaruts, they currently work with Godot 3.1 : ) see #42

**Comment by Zireael07** [comment]
#42 is not merged yet, any reasons why?

**Comment by adrianperreault** [comment]
@Zireael07, the main author of the bindings has commercial code in production that's on an earlier Nim version.

**Comment by Zireael07** [comment]
I thought it was something to do with the PR itself :P
