### ISSUE TITLE
0.20, stub, windows -> cannot open file: engine

### ISSUE THREAD

**Issue by travisstaloch** [pragmagic/godot-nim#44]
I installed godot 3.0 and followed the [godot-nim Getting Started docs](https://pragmagic.github.io/godot-nim/v0.7.8/index.html#getting-started).  I have an existing nim 0.20.0 and nimble.  Trying to build the stub, there were errors.  Using `nimble install https://github.com/aguspiza/godot-nim#head` and `requires "https://github.com/aguspiza/godot-nim#head"` in stub.nimble fixed many of the errors.   

I [forked that repo](https://github.com/travisstaloch/godot-nim) and got through the remaining error and even got rid of warnings which were mostly caused by changes to NimNode after 0.18.  The remaining error involved removing the `{.immediate.}` pragma from the [macro gdobj in godotmacros.nim(630)](https://github.com/aguspiza/godot-nim/blob/master/godot/nim/godotmacros.nim#L630).  I also [forked the stub](https://github.com/travisstaloch/godot-nim-stub) with my change.  

I'm now getting the error:   
> godot-nim-stub\src\fpscounter.nim(5, 8) Error: cannot open file: engine

Any ideas or suggestions?  Do I just need to be on 0.18?  I saw a comment above godotmacros.nim(630) 
```nim
# immediate macros are deprecated, but `untyped` doesn't make it immediate,
# as the warning and the documentation claim.
```

Could this be causing the error I'm seeing?  I don't need to have the [godot_headers](https://github.com/GodotNativeTools/godot_headers) somewhere and pass/include to nim compiler do I?  Hoping there is someway to use 0.20 as choosenim is broken on windows afaik.

**Comment by zetashift** [comment]
You could try the version described here; https://github.com/pragmagic/godot-nim/pull/42 which is located at: https://github.com/bluenote10/godot-nim/tree/attempt_fixes_for_0.19

Or indeed use 0.18 with choosenim, which works on Windows 10(I can tell because I'm currently using choosenim on a 64bit laptop).

**Comment by DwanaG** [comment]
I made a new PR (#45) based on #42. You can use my fork and give it a try. Test is needed!!

**Comment by travisstaloch** [comment]
@DwanaG if I use your branch with:
```nim
# stub.nimble
requires "https://github.com/DwanaG/godot-nim#attempt_fixes_for_0.19"
```
I get the same error as with my patch: 
> ...\godot-nim-stub\src\fpscounter.nim(5, 8) Error: cannot open file: engine

@zetashift when I use:
```nim
# stub.nimble
requires "https://github.com/bluenote10/godot-nim#attempt_fixes_for_0.19"
```
I get:
> ...\githubcom_bluenote10godotnim_#attempt_fixes_for_0.19\godot\nim\godotnim.nim(347, 3) Error: type mismatch: got <string> but expected 'NimNode = ref NimNodeObj'

**Comment by DwanaG** [comment]
> ...\godot-nim-stub\src\fpscounter.nim(5, 8) Error: cannot open file: engine

It seems that Nim cannot find the _godotapi/engine.nim file. Does the _godotapi folder is generated when you compile the project?

**Comment by travisstaloch** [comment]
Yes, I see the _godotapi folder (godot-nim-stub\\_godotapi) with only one file in it, api.json.

**Comment by DwanaG** [comment]
Could you start from a clean project? Delete the _godotapi and .nimcache folders and also nakefile.exe and try again.

**Comment by travisstaloch** [comment]
That worked, generating all of the .nim files in the _godotapi folder.  Now there is an error: 

`...\\godot-nim-stub\\src\\fpscounter.nim(7, 7) template/generic instantiation of gdobj from here  
...\\godot-nim-stub\\src\\fpscounter.nim(11, 15) Error: type mismatch: got \<bool\>
but expected one of:
proc setProcess(self: Node; enable: bool)`

**Comment by DwanaG** [comment]
Previous versions of the bindings used the this:self pragma, which made things easier. Now, that is deprecated and methods must be called explicitly with self. Please check the comment on my PR #45 to see how it's working now. I can't find a way to make it work the way it used to.

**Comment by travisstaloch** [comment]
I was able to get it to build by using `self.setProcess(true)` and also updating the mainpanel.nim file with similar:
```nim
# fpscounter.nim
gdobj FPSCounter of Label:
  var lastFPS: float32

  method ready*() =
    self.setProcess(true)

#mainpanel.nim
gdobj MainPanel of Panel:
  method ready*() =
    self.setProcessInput(true)

  method input*(event: InputEvent) =
    if event of InputEventMouseButton:
      let ev = event as InputEventMouseButton
      if ev.buttonIndex == BUTTON_LEFT:
        self.getTree().setInputAsHandled()
        let scene = load("res://scene.tscn") as PackedScene
        self.getTree().root.addChild(scene.instance())
        self.queueFree()
```

**Comment by travisstaloch** [comment]
It works! Thank you so much for your help.  Now, being a godot newb, I just need to understand how to actually make use this from godot...

**Comment by travisstaloch** [comment]
Actually, nevermind... just launching godot from the godot-nim-stub folder brings the game right up...

**Comment by travisstaloch** [comment]
Should I make a PR for godot-nim-stub with these changes?

**Comment by DwanaG** [comment]
Would be nice. But that's the way it should be done if using my branch. Otherwise the way it is now is cleaner. If you make a PR, probably will be merged only if my PR is merged.

**Comment by zetashift** [comment]
@travisstaloch you can try using: https://github.com/zetashift/godotnim-samples this as a guideline, `dodgethenim` is a Nim version of the `your first game` godot version. Ofcourse you need to add `self` everywhere

**Comment by travisstaloch** [comment]
Ok, I made a [PR](https://github.com/pragmagic/godot-nim-stub/pull/12) in case it ever gets merged.  Thanks again for your help.
