### ISSUE TITLE
nimble installs the 0.3.0 version

### ISSUE THREAD

**Issue by DriNeo** [pragmagic/godot-nim#5]
Hi, I followed the stub project readme to install godot-nim on my Linux machine then nake complains about godotapigen module.

Here is the files installed by nimble.

![capture du 2017-08-02 16-58-04](https://user-images.githubusercontent.com/12350741/28880095-414685d4-77a4-11e7-8e6c-bf65dba318ee.png)

I guess nimble has installed an outdated version.

**Comment by endragor** [comment]
The problem was actually with the stub - it used a new feature it was not supposed to use before the new version is released. I've just released v0.4.0 and updated the stub to use it, please check if it's fine now.

**Comment by DriNeo** [comment]
Nimble has installed the 0.4.0 version and I updated the stub project but build failed for package stub

`/home/drit0/.nimble/pkgs/godot-0.4.0/nim/godotnim.nim(669, 3) Error: undeclared identifier: 'deallocHeap'
stack trace: (most recent call last)
home/drit0/Programmes/Godot3.0/NimGDNativeTest/godot-nim-stub-master/src/stub.nimble(26) makeTask
home/drit0/Programmes/Nim/nim-0.17.0/lib/system/nimscript.nim(206) exec
home/drit0/Programmes/Nim/nim-0.17.0/lib/system/nimscript.nim(206, 7) Error: unhandled exception: FAILED: nimble build -y`

Maybe it's my fault and not related to the issue.

**Comment by TiberiumN** [comment]
@DriNeo do you use another GC?

**Comment by DriNeo** [comment]
@TiberiumN I just entered `nake build` command on a Linux LMDE O.S.

**Comment by endragor** [comment]
@DriNeo This requires Nim devel at the moment. You either use release version or an earlier one.

**Comment by DriNeo** [comment]
Thanks endragor. Finally solved.
