### ISSUE TITLE
Godot 3.1 header support?

### ISSUE THREAD

**Issue by zetashift** [pragmagic/godot-nim#51]
So the GDNative headers are synced with 3.1: https://github.com/GodotNativeTools/godot_headers
Godot-nim docs say that's ment for 3.0. 
Does it matter that gdnative_headers got synced with 3.1, is it a big differencce? Does godot-nim just automagically work with the newest ones?

**Comment by endragor** [comment]
godot-nim does not use the headers. As long as there are no breaking changes in GDNative API (and ABI) comparing to 3.0, everything should continue to work.

**Comment by zetashift** [comment]
Ah thanks for the info!
