### ISSUE TITLE
Getting errors using {.gdExport.} pragma

### ISSUE THREAD

**Issue by Skaruts** [pragmagic/godot-nim#52]
I'm using Godot 3.2_rc1 and Nim 1.0.4 (should I use older versions?)

I'm getting an error when I use `{.gdExport.}` on initialization fields. For example:
```nim
import godot
import godotapi/node_2d

gdobj SimpleTest of Node2D:
    var derp* {.gdExport.} = 10 
```
```
C:\Godot\Godot-Nim\simple_test\src\simple_test.nim(4, 7) 
       template/generic instantiation of `gdobj` from here
C:\Users\Skaruts\.nimble\pkgs\godot-0.7.26\nim\godotmacros.nim(406, 21) 
      Error: undeclared identifier: 'typeInfo`gensym1145165'
```

I also tried using hints and hintStrs, but nothing seemed to work. 

That pragma works on procs though.

**Comment by zetashift** [comment]
Did something change with `static` in Nim? https://github.com/pragmagic/godot-nim/blob/master/godot/nim/godotmacros.nim#L400

**Comment by Skaruts** [comment]
This is a bit out of my league, so I'm shooting blind here, but could this have anything to do with it (from [0.20.0 changelog](https://nim-lang.org/blog/2019/06/06/version-0200-released.html)):

> Macro arguments of type typedesc are now passed to the macro as NimNode like every other type except static. Use typed for a behavior that is identical in new and old Nim. See the RFC [Pass typedesc as NimNode to macros](https://github.com/nim-lang/RFCs/issues/148) for more details.

I did a search for `static` in the changelogs, working backwards from 1.0.4, and that was the first thing I found that might be relevant.

**Comment by zetashift** [comment]
I went through the changelogs too, found the culprit:

> The language definition and compiler are now stricter about gensym'ed symbols in hygienic templates. See the section in the manual for further details. Use the compiler switch --oldgensym:on for a transition period.

 
https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_1_0_0.md
Manual link: https://nim-lang.org/docs/manual.html#templates-hygiene-in-templates

The reason why this is the culprit because I get a succesfull compile adding `--oldgensym:on` to the nakefile. I pushed this switch and some minor changes to dodgethenim.
