### ISSUE TITLE
nake loops forever when something fails

### ISSUE THREAD

**Issue by Skaruts** [pragmagic/godot-nim#53]
Nake keeps trying to repeat the task when something fails. I had to change the line in nakefile.nim...
```nim
direShell(["nimble", "c", ".."/"src"/"stub.nim", "-o:.."/"_dlls"/libFile])
```
to
```nim
shell(["nimble", "c", ".."/"src"/"stub.nim", "-o:.."/"_dlls"/libFile]) 
```
... so that nake quits when the build fails. 

I'm on `Windows 7`, if that makes any difference.

The same thing was happening a few days ago when I had no clue what I was doing, and the effect was that it just kept opening and closing godot on me, over and over, and repeating the message that it couldn't generate `api.json`. 

---

On a related note, when it loops due to failed build it also tries to generate the entire godot api from scratch inside `src\src` folder, because apparently `direShell` never returns and `withDir "src"` is still in effect, and iirc it endlessly creates a new src folder inside the last src folder, each with an entire new godot api inside.

**Comment by zetashift** [comment]
I can't recreate this on either Linux or Windows 10. This might be a Nake/Nim OS module thing on Windows 7, rather than godot-nim.

**Comment by Skaruts** [comment]
Could be. I couldn't find any similar issue on nake's repo, though, but I'll double check. Maybe I could/should open an issue there.

**Comment by Skaruts** [comment]
Gonna just close this, as the problem is probably not relevant here. I haven't been using Godot for a while either, so I'm not sure when I'll come around to report this and know for sure.
