### ISSUE TITLE
Can't build sample app on Mac, environment variable not working

### ISSUE THREAD

**Issue by wyattjsmith1** [pragmagic/godot-nim#58]
Hi, I installed everything according to https://pragmagic.github.io/godot-nim/master/index.html and followed the steps in the README. I get a peculiar error when running `nake build`:

```
➜  platformer-nim nake build
Compiling nakefile...
GODOT_BIN environment variable is not set
➜  platformer-nim echo $GODOT_BIN
/Applications/Godot.app/Contents/MacOS/Godot
➜  platformer-nim
```

As you can see, it is complaining `GODOT_BIN` is not set when it really is. Some info about my computer:
Macos 10.14.6
Tested with both Zsh and Bash

Does anyone have any suggestions for getting around this? Am I setting this up correctly?

**Comment by zetashift** [comment]
I can reproduce this, on Windows x64.
A full restart on my laptop fixed it.... I think this is a `getEnv` from Nim issue.

**Comment by wyattjsmith1** [comment]
I ended up coming back to this, and it seems to be working now. I am able to run the sample app. I'm guessing this was a temporary issue with the compiler or something, but as it seems to be working now, I will close this issue.
