### ISSUE TITLE
How to compile for Android/iOS platforms

### ISSUE THREAD

**Issue by tavurth** [pragmagic/godot-nim#65]
Hi! I've come back to godot-nim after a while away and I'm having difficulty compiling for android devices.

I see you have `when defined(android)`, but it's a little hard for me to figure out how to define `android` in nimlang. I'm guessing it's passing through to `#DEFINE android` from C.

So far running `nake build` correctly creates the gdscript api and the sample project is running well.
I've tried `nake build -d:android` but `echo defined(android)` still returns `false`

Thank you for making a useful nim extension for Godot! :)

**Comment by endragor** [comment]
You should pass `--os:android` to Nim.
