### ISSUE TITLE
cannot build sample

### ISSUE THREAD

**Issue by jeangit** [pragmagic/godot-nim#70]
Hello,

godot-nim : 0.8.1
nim : 4.0rc (installed from gitnim)
godot : 3.2.3

git clone --depth=1 https://github.com/pragmagic/godot-nim-stub.git myproject

$ export GODOT_BIN="$(which godot)"
 echo $GODOT_BIN
/usr/bin/godot

nake seems broken with nim 4.0 : `nake-1.9.3/nakelib.nim(219, 18) Error: undeclared identifier: 'toSeconds'`.

I've tried to switch to nim 1.2.6 :
nake build says : `.nimble/pkgs/compiler-#head/compiler/msgs.nim(13, 19) Error: cannot open file: std/private/miscdollars`

I don't know if `nake` is globally broken (i don't know how to use it, i use nimscripts), though. May be my system.

**Comment by zetashift** [comment]
Heya! I think you mean Nim 1.4.0? 

If you use nim 1.4.0 (stable) and install nake using : `nimble install nake@#head` it should remove the toSeconds error.

**Comment by jeangit** [comment]
thank you zetashift, indeed it was my system.

Yes, i was talking about Nim 1.4.0. I've installed #head branch of nake, and `nake build` works perfectly.
