### ISSUE TITLE
Loading in thread

### ISSUE THREAD

**Issue by kzerot** [pragmagic/godot-nim#71]
Have a problem then loading staff in nim thread. 
Same error with threads and threadpool:
ERROR: : Unhandled Nim exception: /home/murre/.choosenim/toolchains/nim-1.4.0/lib/pure/concurrency/threadpool.nim(370) slave
/home/murre/Git/WayOfMerchant/src/thread_loader.nim(58) threadSceneLoadWrapper
/home/murre/Git/WayOfMerchant/src/thread_loader.nim(36) threadSceneLoad
/home/murre/Git/WayOfMerchant/src/godotapi/resource_loader.nim(132) load
/home/murre/.nimble/pkgs/godot-0.7.28/nim/godotnim.nim(373) getSingleton
/home/murre/.nimble/pkgs/godot-0.7.28/nim/godotnim.nim(302) asNimGodotObject
/home/murre/.nimble/pkgs/godot-0.7.28/nim/godotnim.nim(276) newNimGodotObject
/home/murre/.choosenim/toolchains/nim-1.4.0/lib/system/assertions.nim(30) failedAssertImpl
/home/murre/.choosenim/toolchains/nim-1.4.0/lib/system/assertions.nim(23) raiseAssert
/home/murre/.choosenim/toolchains/nim-1.4.0/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: /home/murre/.nimble/pkgs/godot-0.7.28/nim/godotnim.nim(276, 9) `not classRegistry.isNil`  [AssertionDefect]

Proc I spawn:
`
  proc threadSceneLoad*(data: tuple[p:Point, sceneName:string])  =
    var scene = (load(data.sceneName) as PackedScene).instance()
`
Called from
`
spawn self.threadSceneLoad(args)
`

**Comment by endragor** [comment]
Duplicates #46.
