### ISSUE TITLE
I cannot compile anymore, for some reason

### ISSUE THREAD

**Issue by Skaruts** [pragmagic/godot-nim#72]
It's been quite a while since I last touched godot-nim, and now I went back to it and I'm getting the error below. I tried compiling in several nim versions, and I also installed the latest godot-nim (or at least the latest that nimble found), and I got the same error every time. I'm also getting this error in more than one project.

```
C:\Users\Skaruts\.choosenim\toolchains\nim-1.2.0\lib\nimbase.h(263): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
Error: execution of an external compiler program 'vccexe.exe /c --platform:amd64 /nologo -DWIN32_LEAN_AND_MEAN /Zi /FS /Od  /IC:\Users\Skaruts\.choosenim\toolchains\nim-1.2.0\lib /Ic:\Godot\Godot-Nim\Terminal_Rendering_Tests\src /Foc:\Godot\Godot-Nim\Terminal_Rendering_Tests\src\.nimcache\windows\amd64\stdlib_io.nim.c.obj c:\Godot\Godot-Nim\Terminal_Rendering_Tests\src\.nimcache\windows\amd64\stdlib_io.nim.c' failed with exit code: 2


       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "C:\Users\Skaruts\.nimble\bin\nim.exe" c --noNimblePath -d:NimblePkgVersion=0.1.0 --path:"C:\Users\Skaruts\.nimble\pkgs\godot-0.7.26" --path:"C:\Users\Skaruts\.nimble\pkgs\compiler-1.0.4" "--oldgensym:on" "-o:..\_dlls\nim_64.dll"  "..\src\stub"
```

**Comment by zetashift** [comment]
On windows you'll need Visual Studio Build Tools: https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017
If that still doesn't work try  `src/config.nims` line 41: https://github.com/pragmagic/godot-nim-stub/blob/master/src/config.nims#L41 

change `vcc` to `gcc`

**Comment by Skaruts** [comment]
Changing to gcc worked!

It's weird though, I don't think I removed vs build tools in the meanwhile...

**Comment by zetashift** [comment]
I actually have VS Build Tools installed and I still get an error:
```
C:\Users\Rishi\stack\dev\gamedev\gdquest-course\src\stub.nim(9, 17) Warning: imported and not used: 'player' [UnusedImport]
Hint: vcvarsall.bat was not foundHint: vcvarsall.bat was not found
Hint: vcvarsall.bat was not found
oserr.nim(94)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
Additional info: "Requested command not found: \'cl.exe\'. OS error:" [OSError]
oserr.nim(94)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
Additional info: "Requested command not found: \'cl.exe\'. OS error:" [OSError]
oserr.nim(94)            raiseOSError
Additional info: "Requested command not found: \'cl.exe\'. OS error:" [OSError]

oserr.nim(94)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
Additional info: "Requested command not found: \'cl.exe\'. OS error:" [OSError]
Error: execution of an external compiler program 'vccexe.exe /c --platform:amd64  /nologo -DWIN32_LEAN_AND_MEAN /Zi /FS /Od   /IC:\Users\Rishi\.choosenim\toolchains\nim-1.4.0\lib /IC:\Users\Rishi\stack\dev\gamedev\gdquest-course\src /nologo /FoC:\Users\Rishi\stack\dev\gamedev\gdquest-course\src\.nimcache\windows\amd64\stdlib_io.nim.c.obj C:\Users\Rishi\stack\dev\gamedev\gdquest-course\src\
````

**Comment by zetashift** [comment]
@Skaruts IMHO this issue can be closed, it's not a godot-nim problem, however the docs could mention it as a potentional pitfall on Windows.

**Comment by Skaruts** [comment]
Well iirc I always used the default windows console, and it used to work. I don't think I even changed anything in my system apart from the nim version since the last time, but I could be wrong. 

Anyway, it's working with gcc, so I guess it's fine. (Doesn't generate the `.lib`, `.exp`, `.pdb` and `.ilk` files along with the dll, but I'm not having any issues.)

**Comment by zetashift** [comment]
Personally I think it's a weird environment thing maybe when upgrading a Nim version. Either way godot-nim can't do anything about that.
