### ISSUE TITLE
godot-nim compilation breaks on nim 979148e86

### ISSUE THREAD

**Issue by geekrelief** [pragmagic/godot-nim#81]
~~There's a circular dependency between arrays.nim and poolarrays.nim that no longer compiles properly on nim commit 979148e86 on devel.~~
It's not a circular dependency. nim commit 979148e86 on devel broke the {.pure.} pragma.  So Array defined in the VariantType enum isn't hidden properly so poolarrays.nim can't see arrays.nim's Array definition.

**Comment by geekrelief** [comment]
Here's the error:
```
godot\core\poolarrays.nim(127, 16) template/generic instantiation of `definePoolArray` from here
godot\core\poolarrays.nim(49, 26) Error: type expected, but got symbol 'Array' of kind 'enumField'
```
in poolarrays.nim
```nim
import arrays

definePoolArray(PoolByteArray, GodotPoolByteArray, uint8,
                godotPoolByteArray, newPoolByteArray,
                initGodotPoolByteArray)
```

**Comment by geekrelief** [comment]
I submitted a bug report to nim: https://github.com/nim-lang/Nim/issues/16462

**Comment by geekrelief** [comment]
The latest working commit is: 3b963a81

**Comment by geekrelief** [comment]
I found out the issue is due to {.pure.} pragma https://nim-lang.org/docs/manual.html#pragmas-pure-pragma not working correctly to hide VariantType.Array https://github.com/pragmagic/godot-nim/blob/388bea92053593646518946f6abc1001aea77702/godot/internal/godotinternaltypes.nim#L74
https://github.com/pragmagic/godot-nim/blob/388bea92053593646518946f6abc1001aea77702/godot/internal/godotinternaltypes.nim#L95

When Array is used in the `definePoolArray` template: https://github.com/pragmagic/godot-nim/blob/388bea92053593646518946f6abc1001aea77702/godot/core/poolarrays.nim#L38-L41

Will close the issue once this the nim devs resolve it.

**Comment by geekrelief** [comment]
A workaround is to prefix the VariantType enum entries like vtNil, vtArray, etc.

**Comment by RecruitMain707** [comment]
I get this error again with nim 1.5.1 and godot 3.3.3

**Comment by insomniacUNDERSCORElemon** [comment]
@RecruitMain707 and @cmyka1b2c3d4 make sure you check the stub.nimble file in your project, I was having this issue and it was caused by that file forcing an old version of godot-nim, simply changing the line to `requires "godot >= 0.8.0"` fixed it.
