### ISSUE TITLE
i don't know how to set GODOT_BIN

### ISSUE THREAD

**Issue by DARTHVADERbn** [pragmagic/godot-nim#82]
Windows 10
nimble, nim and nake are installed

in [godot-nim-stub](https://github.com/pragmagic/godot-nim-stub) saying that i need point environment varible to Godot executable.

but how i need to make that, by console command or changing varible in .nim file instead?

**Comment by geekrelief** [comment]
google: "windows environment variables" brings up this useful link https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/

**Comment by DARTHVADERbn** [comment]
Thanks, i'm closing issue
