### ISSUE TITLE
method assumes virtual methods always start with an underscore

### ISSUE THREAD

**Issue by geekrelief** [pragmagic/godot-nim#87]
Example:
EditorPlugin.has_main_screen is a virtual method, but does not have an underscore.
https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#class-editorplugin-method-has-main-screen

```nim
method hasMainScreen():bool = true
```
use of method on a proc assumes it's virtual

https://github.com/pragmagic/godot-nim/blob/388bea92053593646518946f6abc1001aea77702/godot/nim/godotmacros.nim#L165

and gdobj prepends an underscore to all method names.
https://github.com/pragmagic/godot-nim/blob/388bea92053593646518946f6abc1001aea77702/godot/nim/godotmacros.nim#L608

As a work around to override the virtual function you declare it as proc with gdExport like:
```nim
proc hasMainScreen():bool {.gdExport.} =
  true
```

**Comment by endragor** [comment]
You can override the name selected by default, like this: `{.gdExport: "has_main_screen".}`.
`method`s are exported with `_` prepended by default, because that's the convention Godot mostly follows itself. Yes, it's not always that way, and you can override it where needed. If not for this default, you'd have to do `method process() {.gdExport: "_process".}` everywhere, which is annoying.

**Comment by geekrelief** [comment]
I just tried passing a param as you suggested, and it doesn't work.  I must be missing something because I don't see where that's happening in godotmacros.nim.  I see hint and hintStr using `removeStrPragma` to get the value, but gdExport is using `removePragma`:

https://github.com/pragmagic/godot-nim/blob/388bea92053593646518946f6abc1001aea77702/godot/nim/godotmacros.nim#L142

https://github.com/pragmagic/godot-nim/blob/388bea92053593646518946f6abc1001aea77702/godot/nim/godotmacros.nim#L158

**Comment by endragor** [comment]
Ah, maybe I confused this with another project. Well, then I think the way it's described in my previous comment is how this should be resolved.
