### ISSUE TITLE
Rect2 is missing hasPoint

### ISSUE THREAD

**Issue by rosshadden** [pragmagic/godot-nim#9]
`Rect2` is missing `hasPoint`, http://docs.godotengine.org/en/latest/classes/class_rect2.html#class-rect2-has-point

**Comment by rosshadden** [comment]
`Rect3` and `Plane` are as well.

**Comment by karroffel** [comment]
I think it's `contains`, not `hasPoint`. If you take a look at the implementation you see that the C function gets used in the `contains` proc

**Comment by rosshadden** [comment]
Ah, okay thanks @karroffel. I was searching the generated _godotapi files for `has_point` and `contains` and only finding the former for A* and Control.  I didn't also search godot-nim, which is where Rect and the other core types are defined.  Oops!
