### ISSUE TITLE
Error: unhandled exception: index 89678 not in 0 .. 89677 [IndexDefect]

### ISSUE THREAD

**Issue by EmilianaWeiss** [pragmagic/godot-nim#92]
I am try to run a package called lofreq,  and for some reason nim is not working properly.

 ./lofreq viterbi -f=/home/guest1/Desktop/HSA_chr/KY962518_tandem_union.fasta -b='/home/guest1/Desktop/UL_guppy4/HG002_ultra_tandem_filterK.bam' > '/home/guest1/Desktop/UL_guppy4/HG002_ultra_tandem_filterK_viterbi.bam'
/home/guest1/.nimble/pkgs/cligen-1.4.1/cligen.nim(1024) lofreq
/home/guest1/.nimble/pkgs/cligen-1.4.1/cligen.nim(676) multiSubs
/home/guest1/.nimble/pkgs/cligen-1.4.1/cligen.nim(758) multi
/home/guest1/.nimble/pkgs/cligen-1.4.1/cligen.nim(676) dispatchviterbi
/home/guest1/lofreq3/src/lofreqpkg/viterbi.nim(217) viterbi
/home/guest1/lofreq3/src/lofreqpkg/viterbi.nim(59) getRefContext
/home/guest1/nim-1.4.2/lib/system.nim(2496) []
/home/guest1/nim-1.4.2/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index 89678 not in 0 .. 89677 [IndexDefect]

I am using nim-1.4.2.

I have clean the cache, and it still does not work. 

There is anything else that you suggest?

**Comment by zetashift** [comment]
Hiya, godot-nim is related to the Godot game engine, and from your error I can see that you are doing something with sequence aligning?

You should open this issue up in: https://github.com/andreas-wilm/lofreq3 , but from your error I can only get that there is an off by one error somewhere in `viterbi.nim`

**Comment by EmilianaWeiss** [comment]
Thanks! going to do that!
